### ISSUE TITLE
Update runtime to 5.13

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.toggl.TogglDesktop#3]

**Comment by MartinBriza** [comment]
5.13 (and further) don't ship QtWebengine. We're planning to get rid of it anyway so we'll be stuck at 5.12 for a bit and when we get rid of the embedded browser, I'll upgrade the dependency.

**Comment by a-kurau** [comment]
After upgrading to 5.15 flatpak app doesn't work :(

$ flatpak run com.toggl.TogglDesktop
/app/bin/TogglDesktop.sh: line 21: dbus-launch: command not found

Linux Mint 19.3 x64 up to date

$ uname -r
5.4.0-48-generic

$ which dbus-launch
/usr/bin/dbus-launch

$ /usr/bin/dbus-launch --version
D-Bus Message Bus Launcher 1.12.2

**Comment by MartinBriza** [comment]
Hello, @a-kurau . This was reported already and a fix is coming soon, hopefully tomorrow. Sorry for the issues.

As for this bug, it's been fixed already so I'm closing it but please feel free to reopen it or open a new one in case of any further questions or bugs, thank you.
