### ISSUE TITLE
Please consider removing --filesystem=host

### ISSUE THREAD

**Issue by Arxcis** [flathub/com.toggl.TogglDesktop#4]
As a user of this app, I cannot find any rationale for why `com.toggle.TogglDesktop` would require `--filesystem=host` by default.

Please consider removing `--filesystem=host` from the `finish-args` list, if not absolutely required for the app to function :pray: 

Thanks :smiley:

**Comment by Newbytee** [comment]
Upstream has officially made the app stop working as of two days ago: https://support.toggl.com/en/articles/2410832-toggl-track-desktop-app-for-linux-deprecated. Closing this as such.
