### ISSUE TITLE
Wrong tray icon on Ubuntu Budgie 20.04

### ISSUE THREAD

**Issue by matrn** [flathub/com.toggl.TogglDesktop#5]
I installed toggle using flathub `flatpak install flathub com.toggl.TogglDesktop` but when I run it using flatpak:
```
~ $ flatpak run com.toggl.TogglDesktop 
Gtk-Message: 21:41:41.750: Failed to load module "appmenu-gtk-module"
Gtk-Message: 21:41:41.789: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:41:41.789: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Log path  "/home/matej/.var/app/com.toggl.TogglDesktop/data/Toggl/Toggl Desktop/toggldesktop.log"
DB path  "/home/matej/.var/app/com.toggl.TogglDesktop/data/Toggl/Toggl Desktop/toggldesktop.db"
failed to register service "org.kde.StatusNotifierItem-9-1"
```
or using normal desktop shortcut, tray icon is wrong:
![image](https://user-images.githubusercontent.com/43115910/107888317-cd9eec80-6f0b-11eb-966b-22a863e4f294.png)

**System:** `Ubuntu Budgie 20.04.2.0 LTS`

**Comment by Newbytee** [comment]
Upstream has officially made the app stop working as of two days ago: https://support.toggl.com/en/articles/2410832-toggl-track-desktop-app-for-linux-deprecated. Closing this as such.
