### ISSUE TITLE
Possible to create to background instances

### ISSUE THREAD

**Issue by jurf** [flathub/com.toggl.TogglDesktop#6]
I am not sure if the app just doesn’t create a pidfile (I cannot find anything inside `/tmp` in the sandbox) or the package prevents it from being read by another instance.

**Comment by jurf** [comment]
Upstream: https://github.com/toggl-open-source/toggldesktop/issues/4744

**Comment by Newbytee** [comment]
Upstream has officially made the app stop working as of two days ago: https://support.toggl.com/en/articles/2410832-toggl-track-desktop-app-for-linux-deprecated. Closing this as such.
