### ISSUE TITLE
Bering to foreground for idle detection

### ISSUE THREAD

**Issue by rubenvw-ngdata** [flathub/com.toggl.TogglDesktop#7]
I've been using toggl on mac for a long time,
Now that I am using linux (ubuntu 20.04) I find it unfortunate that the idle detection popup does not take focus. I always have to press the shortcut to 'show toggl' first. I've found this really frustrating. Can you fix this?

**Comment by rubenvw-ngdata** [comment]
![image](https://user-images.githubusercontent.com/93343110/146545705-4fcd7474-937d-468d-a39e-3ddb70893bea.png)
I only see this when I bring toggle to focus myself:
![image](https://user-images.githubusercontent.com/93343110/146545854-2e04f85c-54f8-4d75-aa8d-71cef7f73996.png)

**Comment by Newbytee** [comment]
Upstream has officially made the app stop working as of two days ago: https://support.toggl.com/en/articles/2410832-toggl-track-desktop-app-for-linux-deprecated. Closing this as such.
