### ISSUE TITLE
org.kde.Platform//5.15 is end-of-life, how to fix

### ISSUE THREAD

**Issue by cassioborgesmenezes** [flathub/com.toggl.TogglDesktop#8]
Looking for updates…
Info: org.kde.Platform//5.15 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications using this runtime:
   com.toggl.TogglDesktop

**Comment by zink-chimaera** [comment]
I'm not familiar with flatpaks yet. Do we just have to update the json?
I've seen flathub also doesn't use the latest version of Toggl.

I'd be willing to help if I get a small introduction. :beginner: 

@IndrekV @MartinBriza please :pleading_face:

**Comment by MartinBriza** [comment]
I'm no longer involved with the Toggl company and the Linux application has been deprecated by them. I'm not sure if it's worth updating the runtime but I'll check out what I can do later today. Then I'll look into ways of giving up the maintenance of this package-

**Comment by MartinBriza** [comment]
I updated the package to the 5.15-21.08 runtime and everything seems to be in order now. Since I'm no longer affiliated with Toggl, I removed myself from the repository.
